tools: fix frr-reload for unset of ra-interval
ra-interval and ra-lifetime have interdependency.
ra-interval < ra-lifetime.
 when both are configured and later
unset of ra-interval then, ra-interval will be set to default value of
600 sec, which might be greater than configured ra-lifetime.
This causes unset command to fail and hence frr-reload error

Fix: whenever the configs are getting cleaned, process no ra-interval later
than no ra-lifetime.

Ticket: #4345405

Testing:
before:
2025-02-22 06:11:07,397 ERROR: ERROR: SET_CONFIG request failed, Error: YANG error(s):
 Path: Data location "/frr-interface:lib/interface[name='swp1s2']/frr-zebra:zebra/ipv6-router-advertisements/default-lifetime".
 Error: Must condition ". = 0 or . * 1000 >= ../max-rtr-adv-interval" not satisfied.

Signed-off-by: Vijayalaxmi Basavaraj <vbasavaraj@nvidia.com>